# Site settings
title: FilipPwn page
email: filip.bartosz.wozniak@gmail.com
description: >-
        My first page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://filippwn.github.io" # the base hostname & protocol for your site
github_username:  FilipPwn

# Build settings
markdown: kramdown
theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme 

# Other configurations can be added as needed
