source "https://rubygems.org"

# This will help ensure the proper Jekyll version is running.
gem "github-pages", "~> 228", group: :jekyll_plugins

# If you want to change your theme, you may change it here.
gem "minima", "~> 2.0"

# Plugins for Jekyll
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  # Add other plugins here, but make sure they are supported by GitHub Pages
end

# Windows-specific gems
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
